import { Driver, Lorry, Shipment, SystemSettings } from '../optimization/types';

export const SEED_SYSTEM_SETTINGS: SystemSettings = {
  id: 'sys-settings-01',
  fuel_price_per_liter: 96.50, // ₹96.50 / Liter (Standard Indian Commercial Diesel)
  driver_base_rate_per_km: 6.00, // ₹6.00 / km
  operating_cost_per_km: 3.20, // ₹3.20 / km (tires, mechanical maintenance & lubricants)
  fixed_dispatch_cost_per_lorry: 800.00, // ₹800 fixed dispatch overhead
  auto_dispatch_high_priority: false, // Configurable operational auto-dispatch
  route_deviation_threshold_km: 1.5, // 1.5 km corridor deviation alert limit
  weight_fuel_cost: 0.35,
  weight_distance: 0.20,
  weight_deadline_risk: 0.25,
  weight_capacity_utilization: 0.15,
  weight_vehicle_reduction: 0.05,
  average_speed_km_per_h: 48,
  loading_time_minutes: 30,
  service_time_per_stop_mins: 20,
  road_distance_factor: 1.28,
  updated_at: new Date().toISOString(),
};

// Canonical Commercial Fleet Vehicles (L-01 to L-09)
export const SEED_LORRIES: Lorry[] = [
  {
    id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a01',
    lorry_code: 'L-01',
    registration_number: 'TN-04-AZ-8812',
    model: 'Tata Signa 2825.K (Heavy Multi-Axle)',
    max_weight_kg: 25000,
    max_volume_m3: 32,
    fuel_efficiency_km_per_l: 4.5,
    current_lat: 13.0827,
    current_lng: 80.2707,
    current_address: 'Chennai Port CFS Depot, Tamil Nadu',
    status: 'AVAILABLE',
    is_refrigerated: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a02',
    lorry_code: 'L-02',
    registration_number: 'TN-38-BK-4091',
    model: 'Eicher Pro 6028 (Heavy Duty Cargo)',
    max_weight_kg: 28000,
    max_volume_m3: 36,
    fuel_efficiency_km_per_l: 4.8,
    current_lat: 11.0168,
    current_lng: 76.9558,
    current_address: 'Coimbatore SIDCO Industrial Estate, Tamil Nadu',
    status: 'AVAILABLE',
    is_refrigerated: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a03',
    lorry_code: 'L-03',
    registration_number: 'TN-70-CP-9120',
    model: 'Ashok Leyland BOSS 1415 (Medium Duty Freight)',
    max_weight_kg: 14000,
    max_volume_m3: 22,
    fuel_efficiency_km_per_l: 5.8,
    current_lat: 12.7409,
    current_lng: 77.8253,
    current_address: 'Hosur SIPCOT Phase-2 Automotive Complex, Tamil Nadu',
    status: 'AVAILABLE',
    is_refrigerated: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a04',
    lorry_code: 'L-04',
    registration_number: 'KA-01-MJ-5534',
    model: 'BharatBenz 2823R (Container Truck)',
    max_weight_kg: 28000,
    max_volume_m3: 35,
    fuel_efficiency_km_per_l: 4.2,
    current_lat: 12.9716,
    current_lng: 77.5946,
    current_address: 'Peenya Industrial Area Depot, Bengaluru, Karnataka',
    status: 'AVAILABLE',
    is_refrigerated: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a05',
    lorry_code: 'L-05',
    registration_number: 'TN-30-EF-6718',
    model: 'Eicher Pro 3019 (High-Deck ICV)',
    max_weight_kg: 19000,
    max_volume_m3: 26,
    fuel_efficiency_km_per_l: 5.2,
    current_lat: 11.6643,
    current_lng: 78.1460,
    current_address: 'Salem Steel Plant Freight Terminal, Tamil Nadu',
    status: 'AVAILABLE',
    is_refrigerated: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a06',
    lorry_code: 'L-06',
    registration_number: 'TN-58-RT-3209',
    model: 'Tata Ultra T.16 (Refrigerated Cold-Chain Reefer)',
    max_weight_kg: 16000,
    max_volume_m3: 24,
    fuel_efficiency_km_per_l: 6.0,
    current_lat: 9.9252,
    current_lng: 78.1198,
    current_address: 'Madurai Agri-Cold Corridor Hub, Tamil Nadu',
    status: 'AVAILABLE',
    is_refrigerated: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a07',
    lorry_code: 'L-07',
    registration_number: 'TN-45-GH-1188',
    model: 'Mahindra Blazo X 28 (Cargo Hauler)',
    max_weight_kg: 28000,
    max_volume_m3: 36,
    fuel_efficiency_km_per_l: 4.4,
    current_lat: 10.7905,
    current_lng: 78.7047,
    current_address: 'Trichy Central Logistics Yard, Tamil Nadu',
    status: 'AVAILABLE',
    is_refrigerated: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a08',
    lorry_code: 'L-08',
    registration_number: 'TN-23-VX-7440',
    model: 'Ashok Leyland Ecomet 1215 (Express Delivery)',
    max_weight_kg: 12000,
    max_volume_m3: 18,
    fuel_efficiency_km_per_l: 6.5,
    current_lat: 12.9165,
    current_lng: 79.1325,
    current_address: 'Vellore Leather Export SEZ Terminal, Tamil Nadu',
    status: 'AVAILABLE',
    is_refrigerated: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a09',
    lorry_code: 'L-09',
    registration_number: 'TN-42-LK-9033',
    model: 'Eicher Pro 2049 (Light Commercial City Courier)',
    max_weight_kg: 5000,
    max_volume_m3: 10,
    fuel_efficiency_km_per_l: 8.5,
    current_lat: 11.1085,
    current_lng: 77.3411,
    current_address: 'Tiruppur Export Knitwear Logistics Park, Tamil Nadu',
    status: 'AVAILABLE',
    is_refrigerated: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const SEED_DRIVERS: Driver[] = [];
export const SEED_SHIPMENTS: Shipment[] = [];

import {
  MaintenanceRecord,
  FuelRecord,
  ExpenseRecord,
  VehicleDocument,
  DriverDocument,
} from '../optimization/types';

export const SEED_MAINTENANCE_RECORDS: MaintenanceRecord[] = [
  {
    id: 'maint-01',
    lorry_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a01',
    lorry_code: 'L-01',
    service_type: 'REGULAR_SERVICE',
    last_service_date: new Date(Date.now() - 30 * 86400000).toISOString(),
    next_service_date: new Date(Date.now() + 60 * 86400000).toISOString(),
    odometer_km: 42500,
    maintenance_cost_inr: 8500,
    vendor_workshop: 'Tata Authorized Service Center, Chennai Port',
    status: 'COMPLETED',
    notes: 'Standard 40,000 km periodic engine oil and filter replacement.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'maint-02',
    lorry_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a02',
    lorry_code: 'L-02',
    service_type: 'TIRE_ROTATION',
    last_service_date: new Date(Date.now() - 15 * 86400000).toISOString(),
    next_service_date: new Date(Date.now() + 15 * 86400000).toISOString(),
    odometer_km: 58200,
    maintenance_cost_inr: 4200,
    vendor_workshop: 'MRF Tire Care, Coimbatore SIDCO',
    status: 'SCHEDULED',
    notes: 'Front axle tire rotation and wheel alignment check.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'maint-03',
    lorry_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a03',
    lorry_code: 'L-03',
    service_type: 'BRAKE_OVERHAUL',
    last_service_date: new Date(Date.now() - 60 * 86400000).toISOString(),
    next_service_date: new Date(Date.now() - 5 * 86400000).toISOString(),
    odometer_km: 71000,
    maintenance_cost_inr: 12400,
    vendor_workshop: 'Ashok Leyland Workshop, Hosur SEZ',
    status: 'OVERDUE',
    notes: 'Brake liner replacement and pneumatic air valve service.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'maint-04',
    lorry_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a04',
    lorry_code: 'L-04',
    service_type: 'OIL_CHANGE',
    last_service_date: new Date(Date.now() - 5 * 86400000).toISOString(),
    next_service_date: new Date(Date.now() + 90 * 86400000).toISOString(),
    odometer_km: 33400,
    maintenance_cost_inr: 6800,
    vendor_workshop: 'BharatBenz Express Service, Peenya Bengaluru',
    status: 'IN_PROGRESS',
    notes: 'Synthetic lubricant flush and differential oil check.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const SEED_FUEL_RECORDS: FuelRecord[] = [
  {
    id: 'fuel-01',
    lorry_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a01',
    lorry_code: 'L-01',
    driver_name: 'Murugan Selvam',
    date: new Date(Date.now() - 12 * 3600000).toISOString(),
    fuel_quantity_liters: 120,
    fuel_price_per_liter: 96.50,
    total_cost_inr: 11580,
    odometer_km: 42500,
    distance_km: 540,
    efficiency_km_per_l: 4.5,
    fuel_station: 'IndianOil Swagat Highway Hub, NH48 Sriperumbudur',
    created_at: new Date().toISOString(),
  },
  {
    id: 'fuel-02',
    lorry_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a02',
    lorry_code: 'L-02',
    driver_name: 'Ravi Kumar',
    date: new Date(Date.now() - 24 * 3600000).toISOString(),
    fuel_quantity_liters: 140,
    fuel_price_per_liter: 96.50,
    total_cost_inr: 13510,
    odometer_km: 58200,
    distance_km: 672,
    efficiency_km_per_l: 4.8,
    fuel_station: 'Bharat Petroleum COCO, NH544 Salem Bypass',
    created_at: new Date().toISOString(),
  },
  {
    id: 'fuel-03',
    lorry_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a03',
    lorry_code: 'L-03',
    driver_name: 'Suresh Raina',
    date: new Date(Date.now() - 48 * 3600000).toISOString(),
    fuel_quantity_liters: 85,
    fuel_price_per_liter: 96.50,
    total_cost_inr: 8202,
    odometer_km: 71000,
    distance_km: 493,
    efficiency_km_per_l: 5.8,
    fuel_station: 'HPCL Highway Plaza, NH44 Krishnagiri',
    created_at: new Date().toISOString(),
  },
  {
    id: 'fuel-04',
    lorry_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a04',
    lorry_code: 'L-04',
    driver_name: 'Anand Chandran',
    date: new Date(Date.now() - 72 * 3600000).toISOString(),
    fuel_quantity_liters: 160,
    fuel_price_per_liter: 96.50,
    total_cost_inr: 15440,
    odometer_km: 33400,
    distance_km: 672,
    efficiency_km_per_l: 4.2,
    fuel_station: 'Shell Commercial Depot, Electronic City Bengaluru',
    created_at: new Date().toISOString(),
  },
];

export const SEED_EXPENSES: ExpenseRecord[] = [
  {
    id: 'exp-01',
    lorry_code: 'L-01',
    driver_name: 'Murugan Selvam',
    category: 'TOLL',
    amount_inr: 1240,
    date: new Date(Date.now() - 12 * 3600000).toISOString(),
    description: 'FASTag Auto-Debit: Chennai-Bengaluru NH48 Corridor (Sriperumbudur & Nemili Plaza)',
    created_at: new Date().toISOString(),
  },
  {
    id: 'exp-02',
    lorry_code: 'L-02',
    driver_name: 'Ravi Kumar',
    category: 'DRIVER_ALLOWANCE',
    amount_inr: 950,
    date: new Date(Date.now() - 24 * 3600000).toISOString(),
    description: 'Overnight transit bata & night allowance for Coimbatore to Chennai Port trip',
    created_at: new Date().toISOString(),
  },
  {
    id: 'exp-03',
    lorry_code: 'L-03',
    driver_name: 'Suresh Raina',
    category: 'LOADING_UNLOADING',
    amount_inr: 1600,
    date: new Date(Date.now() - 36 * 3600000).toISOString(),
    description: 'CFS Warehouse forklift charges & labor loading tariff at Hosur SEZ',
    created_at: new Date().toISOString(),
  },
  {
    id: 'exp-04',
    lorry_code: 'L-04',
    driver_name: 'Anand Chandran',
    category: 'PARKING',
    amount_inr: 450,
    date: new Date(Date.now() - 48 * 3600000).toISOString(),
    description: 'Secured logistics terminal overnight staging parking at Peenya Industrial Depot',
    created_at: new Date().toISOString(),
  },
];

export const SEED_VEHICLE_DOCS: VehicleDocument[] = [
  {
    id: 'vdoc-01',
    lorry_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a01',
    lorry_code: 'L-01',
    document_type: 'INSURANCE',
    document_number: 'NEWIND-CV-998822',
    issue_date: '2025-06-15',
    expiry_date: '2026-06-14',
    status: 'VALID',
    notes: 'Comprehensive Commercial Fleet Policy (The New India Assurance)',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'vdoc-02',
    lorry_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a01',
    lorry_code: 'L-01',
    document_type: 'FITNESS',
    document_number: 'TN04-FC-2025-8812',
    issue_date: '2025-04-10',
    expiry_date: '2026-04-09',
    status: 'EXPIRING_SOON',
    notes: 'RTO Commercial Fitness Certificate (Valid for 1 Year)',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'vdoc-03',
    lorry_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a02',
    lorry_code: 'L-02',
    document_type: 'PERMIT',
    document_number: 'NP-TN-2024-4091-ALL',
    issue_date: '2024-08-01',
    expiry_date: '2029-07-31',
    status: 'VALID',
    notes: 'All-India National Goods Transit Permit (5 Years)',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'vdoc-04',
    lorry_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a03',
    lorry_code: 'L-03',
    document_type: 'POLLUTION',
    document_number: 'PUCC-TN70-9120-2025',
    issue_date: '2025-08-10',
    expiry_date: '2026-02-10',
    status: 'EXPIRED',
    notes: 'Emission Under Control Certificate (Expired — Scheduled for renewal)',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'vdoc-05',
    lorry_id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a04',
    lorry_code: 'L-04',
    document_type: 'RC',
    document_number: 'RC-KA01-MJ5534-COM',
    issue_date: '2023-01-20',
    expiry_date: '2038-01-19',
    status: 'VALID',
    notes: 'Commercial Heavy Goods Vehicle Registration Certificate',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const SEED_DRIVER_DOCS: DriverDocument[] = [
  {
    id: 'ddoc-01',
    driver_id: 'driver-01',
    driver_name: 'Murugan Selvam',
    document_type: 'DRIVING_LICENSE',
    document_number: 'TN01-2010004921-HMV',
    issue_date: '2010-05-12',
    expiry_date: '2030-05-11',
    status: 'VALID',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ddoc-02',
    driver_id: 'driver-01',
    driver_name: 'Murugan Selvam',
    document_type: 'MEDICAL_FITNESS',
    document_number: 'MED-FIT-2025-0492',
    issue_date: '2025-01-15',
    expiry_date: '2026-01-14',
    status: 'EXPIRING_SOON',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ddoc-03',
    driver_id: 'driver-02',
    driver_name: 'Ravi Kumar',
    document_type: 'DRIVING_LICENSE',
    document_number: 'TN38-2015008311-TRANS',
    issue_date: '2015-08-20',
    expiry_date: '2035-08-19',
    status: 'VALID',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ddoc-04',
    driver_id: 'driver-03',
    driver_name: 'Suresh Raina',
    document_type: 'ID_PROOF',
    document_number: 'AADHAAR-XXXX-XXXX-8912',
    issue_date: '2018-03-01',
    expiry_date: '2099-12-31',
    status: 'VALID',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
