import { Driver, Lorry, Shipment, SystemSettings } from '../optimization/types';

export const SEED_SYSTEM_SETTINGS: SystemSettings = {
  id: 'sys-settings-01',
  fuel_price_per_liter: 96.50, // ₹96.50 / Liter (Standard Indian Commercial Diesel)
  driver_base_rate_per_km: 6.00, // ₹6.00 / km
  operating_cost_per_km: 3.20, // ₹3.20 / km (tires, mechanical maintenance & lubricants)
  fixed_dispatch_cost_per_lorry: 800.00, // ₹800 fixed dispatch overhead
  auto_dispatch_high_priority: false, // Configurable operational auto-dispatch
  route_deviation_threshold_km: 1.5, // 1.5 km corridor deviation alert limit
  weight_fuel_cost: 0.35,
  weight_distance: 0.20,
  weight_deadline_risk: 0.25,
  weight_capacity_utilization: 0.15,
  weight_vehicle_reduction: 0.05,
  average_speed_km_per_h: 48,
  loading_time_minutes: 30,
  service_time_per_stop_mins: 20,
  road_distance_factor: 1.28,
  updated_at: new Date().toISOString(),
};

// Canonical Commercial Fleet Vehicles (L-01 to L-09)
export const SEED_LORRIES: Lorry[] = [
  {
    id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a01',
    lorry_code: 'L-01',
    registration_number: 'TN-04-AZ-8812',
    model: 'Tata Signa 2825.K (Heavy Multi-Axle)',
    max_weight_kg: 25000,
    max_volume_m3: 32,
    fuel_efficiency_km_per_l: 4.5,
    current_lat: 13.0827,
    current_lng: 80.2707,
    current_address: 'Chennai Port CFS Depot, Tamil Nadu',
    status: 'AVAILABLE',
    is_refrigerated: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a02',
    lorry_code: 'L-02',
    registration_number: 'TN-38-BK-4091',
    model: 'Eicher Pro 6028 (Heavy Duty Cargo)',
    max_weight_kg: 28000,
    max_volume_m3: 36,
    fuel_efficiency_km_per_l: 4.8,
    current_lat: 11.0168,
    current_lng: 76.9558,
    current_address: 'Coimbatore SIDCO Industrial Estate, Tamil Nadu',
    status: 'AVAILABLE',
    is_refrigerated: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a03',
    lorry_code: 'L-03',
    registration_number: 'TN-70-CP-9120',
    model: 'Ashok Leyland BOSS 1415 (Medium Duty Freight)',
    max_weight_kg: 14000,
    max_volume_m3: 22,
    fuel_efficiency_km_per_l: 5.8,
    current_lat: 12.7409,
    current_lng: 77.8253,
    current_address: 'Hosur SIPCOT Phase-2 Automotive Complex, Tamil Nadu',
    status: 'AVAILABLE',
    is_refrigerated: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a04',
    lorry_code: 'L-04',
    registration_number: 'KA-01-MJ-5534',
    model: 'BharatBenz 2823R (Container Truck)',
    max_weight_kg: 28000,
    max_volume_m3: 35,
    fuel_efficiency_km_per_l: 4.2,
    current_lat: 12.9716,
    current_lng: 77.5946,
    current_address: 'Peenya Industrial Area Depot, Bengaluru, Karnataka',
    status: 'AVAILABLE',
    is_refrigerated: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a05',
    lorry_code: 'L-05',
    registration_number: 'TN-30-EF-6718',
    model: 'Eicher Pro 3019 (High-Deck ICV)',
    max_weight_kg: 19000,
    max_volume_m3: 26,
    fuel_efficiency_km_per_l: 5.2,
    current_lat: 11.6643,
    current_lng: 78.1460,
    current_address: 'Salem Steel Plant Freight Terminal, Tamil Nadu',
    status: 'AVAILABLE',
    is_refrigerated: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a06',
    lorry_code: 'L-06',
    registration_number: 'TN-58-RT-3209',
    model: 'Tata Ultra T.16 (Refrigerated Cold-Chain Reefer)',
    max_weight_kg: 16000,
    max_volume_m3: 24,
    fuel_efficiency_km_per_l: 6.0,
    current_lat: 9.9252,
    current_lng: 78.1198,
    current_address: 'Madurai Agri-Cold Corridor Hub, Tamil Nadu',
    status: 'AVAILABLE',
    is_refrigerated: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a07',
    lorry_code: 'L-07',
    registration_number: 'TN-45-GH-1188',
    model: 'Mahindra Blazo X 28 (Cargo Hauler)',
    max_weight_kg: 28000,
    max_volume_m3: 36,
    fuel_efficiency_km_per_l: 4.4,
    current_lat: 10.7905,
    current_lng: 78.7047,
    current_address: 'Trichy Central Logistics Yard, Tamil Nadu',
    status: 'AVAILABLE',
    is_refrigerated: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a08',
    lorry_code: 'L-08',
    registration_number: 'TN-23-VX-7440',
    model: 'Ashok Leyland Ecomet 1215 (Express Delivery)',
    max_weight_kg: 12000,
    max_volume_m3: 18,
    fuel_efficiency_km_per_l: 6.5,
    current_lat: 12.9165,
    current_lng: 79.1325,
    current_address: 'Vellore Leather Export SEZ Terminal, Tamil Nadu',
    status: 'AVAILABLE',
    is_refrigerated: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a09',
    lorry_code: 'L-09',
    registration_number: 'TN-42-LK-9033',
    model: 'Eicher Pro 2049 (Light Commercial City Courier)',
    max_weight_kg: 5000,
    max_volume_m3: 10,
    fuel_efficiency_km_per_l: 8.5,
    current_lat: 11.1085,
    current_lng: 77.3411,
    current_address: 'Tiruppur Export Knitwear Logistics Park, Tamil Nadu',
    status: 'AVAILABLE',
    is_refrigerated: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const SEED_DRIVERS: Driver[] = [];
export const SEED_SHIPMENTS: Shipment[] = [];
