import { Driver, Lorry, Shipment, SystemSettings } from '../optimization/types';

export const SEED_SYSTEM_SETTINGS: SystemSettings = {
  id: 'sys-settings-01',
  fuel_price_per_liter: 96.50, // ₹96.50 / Liter (Standard Indian Commercial Diesel)
  driver_base_rate_per_km: 6.00, // ₹6.00 / km
  operating_cost_per_km: 3.20, // ₹3.20 / km (tires, mechanical maintenance & lubricants)
  fixed_dispatch_cost_per_lorry: 800.00, // ₹800 fixed dispatch overhead
  auto_dispatch_high_priority: false, // Configurable operational auto-dispatch
  route_deviation_threshold_km: 1.5, // 1.5 km corridor deviation alert limit
  weight_fuel_cost: 0.35,
  weight_distance: 0.20,
  weight_deadline_risk: 0.25,
  weight_capacity_utilization: 0.15,
  weight_vehicle_reduction: 0.05,
  average_speed_km_per_h: 48,
  loading_time_minutes: 30,
  service_time_per_stop_mins: 20,
  road_distance_factor: 1.28,
  updated_at: new Date().toISOString(),
};

// 24 Realistically Configured Lorries
export const SEED_LORRIES: Lorry[] = [
  // Killer Demo Pair
  {
    id: 'lorry-01',
    lorry_code: 'L-11',
    registration_number: 'TN-01-AB-4501',
    model: 'Tata 1109 LPT (6 Ton)',
    image_url: 'https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=600&auto=format&fit=crop&q=80',
    max_weight_kg: 6000,
    max_volume_m3: 22.0,
    fuel_efficiency_km_per_l: 5.0, // Low efficiency
    current_lat: 13.0450,
    current_lng: 80.2010,
    current_address: 'Guindy Industrial Estate, Chennai',
    status: 'AVAILABLE',
    driver_id: 'driver-01',
    assigned_driver_name: 'Murugan Selvam',
    is_refrigerated: false,
    engine_status: 'UNKNOWN',
    engine_source: 'MANUAL',
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'lorry-02',
    lorry_code: 'L-18',
    registration_number: 'TN-02-CD-8818',
    model: 'Eicher Pro 2059 (Eco-Max 6 Ton)',
    max_weight_kg: 6200,
    max_volume_m3: 24.0,
    fuel_efficiency_km_per_l: 10.4, // High efficiency (Killer Demo winner!)
    current_lat: 13.0850,
    current_lng: 80.1250,
    current_address: 'Ambattur Industrial Estate, Chennai',
    status: 'AVAILABLE',
    driver_id: 'driver-02',
    assigned_driver_name: 'Rajesh Kumar',
    is_refrigerated: false,
    created_at: new Date(Date.now() - 28 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'lorry-03',
    lorry_code: 'L-07',
    registration_number: 'TN-09-EF-1907',
    model: 'BharatBenz 1217R (8 Ton)',
    max_weight_kg: 8500,
    max_volume_m3: 32.0,
    fuel_efficiency_km_per_l: 6.2,
    current_lat: 12.9810,
    current_lng: 80.1800,
    current_address: 'Pallavaram Transport Hub, Chennai',
    status: 'AVAILABLE',
    driver_id: 'driver-03',
    assigned_driver_name: 'Karthik Raja',
    is_refrigerated: false,
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'lorry-04',
    lorry_code: 'L-04',
    registration_number: 'KA-01-GH-3304',
    model: 'Tata Ace Gold (1.2 Ton)',
    max_weight_kg: 1200,
    max_volume_m3: 5.5,
    fuel_efficiency_km_per_l: 14.5,
    current_lat: 12.9350,
    current_lng: 77.6240,
    current_address: 'Koramangala Logistics Hub, Bengaluru',
    status: 'AVAILABLE',
    driver_id: 'driver-04',
    assigned_driver_name: 'Suresh Gowda',
    is_refrigerated: false,
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'lorry-05',
    lorry_code: 'L-05',
    registration_number: 'KA-05-JK-9905',
    model: 'Ashok Leyland Dost+ (1.5 Ton)',
    max_weight_kg: 1500,
    max_volume_m3: 6.8,
    fuel_efficiency_km_per_l: 12.8,
    current_lat: 12.9716,
    current_lng: 77.5946,
    current_address: 'Majestic Central Hub, Bengaluru',
    status: 'AVAILABLE',
    driver_id: 'driver-05',
    assigned_driver_name: 'Venkatesh Rao',
    is_refrigerated: false,
    created_at: new Date(Date.now() - 19 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'lorry-06',
    lorry_code: 'L-06',
    registration_number: 'TN-38-LM-7706',
    model: 'Tata Signa 2823 (18 Ton Multi-Axle)',
    max_weight_kg: 18500,
    max_volume_m3: 46.0,
    fuel_efficiency_km_per_l: 4.1,
    current_lat: 11.0168,
    current_lng: 76.9558,
    current_address: 'Peelamedu Warehousing, Coimbatore',
    status: 'AVAILABLE',
    driver_id: 'driver-06',
    assigned_driver_name: 'Palanisamy Velu',
    is_refrigerated: false,
    created_at: new Date(Date.now() - 18 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'lorry-07',
    lorry_code: 'L-08',
    registration_number: 'TN-47-NO-5508',
    model: 'Eicher Pro 3015 (10.5 Ton)',
    max_weight_kg: 10500,
    max_volume_m3: 36.0,
    fuel_efficiency_km_per_l: 6.8,
    current_lat: 10.9601,
    current_lng: 78.0766,
    current_address: 'Karur Textile Freight Terminal, Karur',
    status: 'AVAILABLE',
    driver_id: 'driver-07',
    assigned_driver_name: 'Annamalai Chettiar',
    is_refrigerated: false,
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'lorry-08',
    lorry_code: 'L-09',
    registration_number: 'TN-58-PQ-2209',
    model: 'Mahindra Bolero Maxi Truck (1.8 Ton)',
    max_weight_kg: 1800,
    max_volume_m3: 7.5,
    fuel_efficiency_km_per_l: 11.8,
    current_lat: 9.9252,
    current_lng: 78.1198,
    current_address: 'Madurai Bypass Logistics Park, Madurai',
    status: 'AVAILABLE',
    driver_id: 'driver-08',
    assigned_driver_name: 'Sundaram Pandian',
    is_refrigerated: false,
    created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'lorry-09',
    lorry_code: 'L-10',
    registration_number: 'TN-27-RS-8810',
    model: 'BharatBenz 2823C (16 Ton Tipper/Cargo)',
    max_weight_kg: 16000,
    max_volume_m3: 40.0,
    fuel_efficiency_km_per_l: 4.5,
    current_lat: 11.6643,
    current_lng: 78.1460,
    current_address: 'Salem Steel & Logistics Zone, Salem',
    status: 'AVAILABLE',
    driver_id: 'driver-09',
    assigned_driver_name: 'Gopalakrishnan V',
    is_refrigerated: false,
    created_at: new Date(Date.now() - 12 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'lorry-10',
    lorry_code: 'L-12',
    registration_number: 'KA-51-TU-6612',
    model: 'Tata 407 Gold SFC (2.5 Ton Reefer)',
    max_weight_kg: 2500,
    max_volume_m3: 10.0,
    fuel_efficiency_km_per_l: 9.2,
    current_lat: 12.8399,
    current_lng: 77.6770,
    current_address: 'Electronic City Phase 2, Hosur Corridor',
    status: 'AVAILABLE',
    driver_id: 'driver-10',
    assigned_driver_name: 'Manjunath Reddy',
    is_refrigerated: true,
    created_at: new Date(Date.now() - 11 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'lorry-11',
    lorry_code: 'L-13',
    registration_number: 'TS-09-VW-4413',
    model: 'Ashok Leyland Ecomet 1215 (7.5 Ton)',
    max_weight_kg: 7500,
    max_volume_m3: 26.0,
    fuel_efficiency_km_per_l: 6.9,
    current_lat: 17.3850,
    current_lng: 78.4867,
    current_address: 'Autonagar Logistics Yard, Hyderabad',
    status: 'AVAILABLE',
    driver_id: 'driver-11',
    assigned_driver_name: 'Srinivasa Rao G',
    is_refrigerated: false,
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'lorry-12',
    lorry_code: 'L-14',
    registration_number: 'MH-12-XY-1114',
    model: 'Eicher Pro 6028 (19 Ton Multi-Axle)',
    max_weight_kg: 19000,
    max_volume_m3: 48.0,
    fuel_efficiency_km_per_l: 3.9,
    current_lat: 18.5204,
    current_lng: 73.8567,
    current_address: 'Chakan MIDC Phase 2, Pune',
    status: 'AVAILABLE',
    driver_id: 'driver-12',
    assigned_driver_name: 'Sachin Shinde',
    is_refrigerated: false,
    created_at: new Date(Date.now() - 9 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'lorry-13',
    lorry_code: 'L-15',
    registration_number: 'TN-04-ZA-3315',
    model: 'Tata Ace EV (1 Ton)',
    max_weight_kg: 1000,
    max_volume_m3: 4.8,
    fuel_efficiency_km_per_l: 16.0, // Equivalent km/L
    current_lat: 13.0827,
    current_lng: 80.2707,
    current_address: 'Chennai Central Parcel Yard',
    status: 'AVAILABLE',
    driver_id: 'driver-13',
    assigned_driver_name: 'Devanathan K',
    is_refrigerated: false,
    created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'lorry-14',
    lorry_code: 'L-16',
    registration_number: 'TN-10-BC-7716',
    model: 'Ashok Leyland Boss 1415 (9 Ton)',
    max_weight_kg: 9200,
    max_volume_m3: 31.0,
    fuel_efficiency_km_per_l: 6.4,
    current_lat: 12.9249,
    current_lng: 80.1000,
    current_address: 'Tambaram Freight Station, Chennai',
    status: 'AVAILABLE',
    driver_id: 'driver-14',
    assigned_driver_name: 'Praveen Chandran',
    is_refrigerated: false,
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'lorry-15',
    lorry_code: 'L-17',
    registration_number: 'KA-04-DE-9917',
    model: 'Tata Ultra T.7 (4 Ton)',
    max_weight_kg: 4000,
    max_volume_m3: 15.0,
    fuel_efficiency_km_per_l: 8.5,
    current_lat: 13.0358,
    current_lng: 77.5970,
    current_address: 'Hebbal Flyover Depot, Bengaluru',
    status: 'AVAILABLE',
    driver_id: 'driver-15',
    assigned_driver_name: 'Harish Babu',
    is_refrigerated: false,
    created_at: new Date(Date.now() - 6 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'lorry-16',
    lorry_code: 'L-19',
    registration_number: 'TN-42-FG-5519',
    model: 'Mahindra Furio 11 (7 Ton)',
    max_weight_kg: 7000,
    max_volume_m3: 24.0,
    fuel_efficiency_km_per_l: 7.1,
    current_lat: 11.1085,
    current_lng: 77.3411,
    current_address: 'Tirupur Apparel Logistics Hub',
    status: 'AVAILABLE',
    driver_id: 'driver-16',
    assigned_driver_name: 'Chandrasekar P',
    is_refrigerated: false,
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'lorry-17',
    lorry_code: 'L-20',
    registration_number: 'TN-33-HI-2220',
    model: 'BharatBenz 1617R (10 Ton Reefer)',
    max_weight_kg: 10000,
    max_volume_m3: 35.0,
    fuel_efficiency_km_per_l: 5.8,
    current_lat: 11.3410,
    current_lng: 77.7172,
    current_address: 'Erode Agro-Reefer Terminal',
    status: 'AVAILABLE',
    driver_id: 'driver-17',
    assigned_driver_name: 'Nagarajan Swami',
    is_refrigerated: true,
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'lorry-18',
    lorry_code: 'L-21',
    registration_number: 'TN-67-JK-8821',
    model: 'Eicher Pro 2049 (2.7 Ton)',
    max_weight_kg: 2700,
    max_volume_m3: 11.0,
    fuel_efficiency_km_per_l: 10.0,
    current_lat: 9.5916,
    current_lng: 77.9511,
    current_address: 'Virudhunagar Trade Center',
    status: 'AVAILABLE',
    driver_id: 'driver-18',
    assigned_driver_name: 'Kandasamy M',
    is_refrigerated: false,
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  // Inactive / Maintenance / On-route vehicles for realistic operational state
  {
    id: 'lorry-19',
    lorry_code: 'L-22',
    registration_number: 'TN-05-LM-4422',
    model: 'Tata Prima 3530.K (24 Ton Heavy Trailer)',
    max_weight_kg: 24000,
    max_volume_m3: 54.0,
    fuel_efficiency_km_per_l: 3.4,
    current_lat: 13.0827,
    current_lng: 80.2707,
    current_address: 'Chennai Port Container Terminal',
    status: 'MAINTENANCE',
    driver_id: null,
    is_refrigerated: false,
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'lorry-20',
    lorry_code: 'L-23',
    registration_number: 'KA-03-NO-7723',
    model: 'Ashok Leyland 4220 (28 Ton Multi-Axle)',
    max_weight_kg: 28000,
    max_volume_m3: 60.0,
    fuel_efficiency_km_per_l: 3.2,
    current_lat: 12.9716,
    current_lng: 77.5946,
    current_address: 'Whitefield Inland Container Depot',
    status: 'UNAVAILABLE',
    driver_id: null,
    is_refrigerated: false,
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'lorry-21',
    lorry_code: 'L-24',
    registration_number: 'TN-11-PQ-9924',
    model: 'Eicher Pro 1049 (2 Ton)',
    max_weight_kg: 2000,
    max_volume_m3: 8.5,
    fuel_efficiency_km_per_l: 11.2,
    current_lat: 12.9180,
    current_lng: 80.1400,
    current_address: 'Chromepet Delivery Yard, Chennai',
    status: 'AVAILABLE',
    driver_id: 'driver-21',
    assigned_driver_name: 'Vijay Shanthi',
    is_refrigerated: false,
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'lorry-22',
    lorry_code: 'L-25',
    registration_number: 'TN-72-RS-1125',
    model: 'Tata LPT 1618 (11 Ton)',
    max_weight_kg: 11000,
    max_volume_m3: 38.0,
    fuel_efficiency_km_per_l: 5.6,
    current_lat: 8.7139,
    current_lng: 77.7567,
    current_address: 'Tirunelveli High-Way Depot',
    status: 'AVAILABLE',
    driver_id: 'driver-22',
    assigned_driver_name: 'Shankar Lingam',
    is_refrigerated: false,
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'lorry-23',
    lorry_code: 'L-26',
    registration_number: 'TN-88-TU-3326',
    model: 'Ashok Leyland Partner (4.5 Ton)',
    max_weight_kg: 4500,
    max_volume_m3: 16.5,
    fuel_efficiency_km_per_l: 8.8,
    current_lat: 10.7905,
    current_lng: 78.7047,
    current_address: 'Thanjavur Agro Terminal',
    status: 'AVAILABLE',
    driver_id: 'driver-23',
    assigned_driver_name: 'Arockiasamy T',
    is_refrigerated: false,
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'lorry-24',
    lorry_code: 'L-27',
    registration_number: 'TN-45-VW-6627',
    model: 'BharatBenz 1923R (12.5 Ton)',
    max_weight_kg: 12500,
    max_volume_m3: 42.0,
    fuel_efficiency_km_per_l: 5.2,
    current_lat: 10.7870,
    current_lng: 79.1378,
    current_address: 'Trichy BHEL Cargo Complex',
    status: 'AVAILABLE',
    driver_id: 'driver-24',
    assigned_driver_name: 'Ramanathan Iyer',
    is_refrigerated: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

// 32 Drivers with phone numbers, shift times, and locations
export const SEED_DRIVERS: Driver[] = [
  { id: 'driver-01', name: 'Murugan Selvam', phone: '+91 98401 23450', license_number: 'TN-01-2015-00124', current_lat: 13.0450, current_lng: 80.2010, availability_status: 'AVAILABLE', shift_start: '06:00', shift_end: '18:00', assigned_lorry_id: 'lorry-01', performance_score: 94, total_deliveries: 428, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'driver-02', name: 'Rajesh Kumar', phone: '+91 98402 34561', license_number: 'TN-02-2016-00567', current_lat: 13.0850, current_lng: 80.1250, availability_status: 'AVAILABLE', shift_start: '06:00', shift_end: '18:00', assigned_lorry_id: 'lorry-02', performance_score: 98, total_deliveries: 612, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'driver-03', name: 'Karthik Raja', phone: '+91 98403 45672', license_number: 'TN-09-2018-00912', current_lat: 12.9810, current_lng: 80.1800, availability_status: 'AVAILABLE', shift_start: '07:00', shift_end: '19:00', assigned_lorry_id: 'lorry-03', performance_score: 91, total_deliveries: 340, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'driver-04', name: 'Suresh Gowda', phone: '+91 98801 11223', license_number: 'KA-01-2017-00334', current_lat: 12.9350, current_lng: 77.6240, availability_status: 'AVAILABLE', shift_start: '06:00', shift_end: '18:00', assigned_lorry_id: 'lorry-04', performance_score: 96, total_deliveries: 510, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'driver-05', name: 'Venkatesh Rao', phone: '+91 98802 22334', license_number: 'KA-05-2014-00891', current_lat: 12.9716, current_lng: 77.5946, availability_status: 'AVAILABLE', shift_start: '08:00', shift_end: '20:00', assigned_lorry_id: 'lorry-05', performance_score: 89, total_deliveries: 780, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'driver-06', name: 'Palanisamy Velu', phone: '+91 94431 33445', license_number: 'TN-38-2013-00445', current_lat: 11.0168, current_lng: 76.9558, availability_status: 'AVAILABLE', shift_start: '05:00', shift_end: '17:00', assigned_lorry_id: 'lorry-06', performance_score: 95, total_deliveries: 890, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'driver-07', name: 'Annamalai Chettiar', phone: '+91 94432 44556', license_number: 'TN-47-2016-00778', current_lat: 10.9601, current_lng: 78.0766, availability_status: 'AVAILABLE', shift_start: '06:00', shift_end: '18:00', assigned_lorry_id: 'lorry-07', performance_score: 92, total_deliveries: 415, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'driver-08', name: 'Sundaram Pandian', phone: '+91 94433 55667', license_number: 'TN-58-2015-00223', current_lat: 9.9252, current_lng: 78.1198, availability_status: 'AVAILABLE', shift_start: '07:00', shift_end: '19:00', assigned_lorry_id: 'lorry-08', performance_score: 93, total_deliveries: 520, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'driver-09', name: 'Gopalakrishnan V', phone: '+91 94434 66778', license_number: 'TN-27-2017-00991', current_lat: 11.6643, current_lng: 78.1460, availability_status: 'AVAILABLE', shift_start: '06:00', shift_end: '18:00', assigned_lorry_id: 'lorry-09', performance_score: 90, total_deliveries: 310, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'driver-10', name: 'Manjunath Reddy', phone: '+91 98803 77889', license_number: 'KA-51-2018-00112', current_lat: 12.8399, current_lng: 77.6770, availability_status: 'AVAILABLE', shift_start: '06:00', shift_end: '18:00', assigned_lorry_id: 'lorry-10', performance_score: 97, total_deliveries: 445, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'driver-11', name: 'Srinivasa Rao G', phone: '+91 99891 88990', license_number: 'TS-09-2014-00665', current_lat: 17.3850, current_lng: 78.4867, availability_status: 'AVAILABLE', shift_start: '06:00', shift_end: '18:00', assigned_lorry_id: 'lorry-11', performance_score: 94, total_deliveries: 620, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'driver-12', name: 'Sachin Shinde', phone: '+91 98220 99001', license_number: 'MH-12-2015-00443', current_lat: 18.5204, current_lng: 73.8567, availability_status: 'AVAILABLE', shift_start: '07:00', shift_end: '19:00', assigned_lorry_id: 'lorry-12', performance_score: 93, total_deliveries: 505, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'driver-13', name: 'Devanathan K', phone: '+91 98404 12345', license_number: 'TN-04-2019-00332', current_lat: 13.0827, current_lng: 80.2707, availability_status: 'AVAILABLE', shift_start: '08:00', shift_end: '20:00', assigned_lorry_id: 'lorry-13', performance_score: 96, total_deliveries: 280, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'driver-14', name: 'Praveen Chandran', phone: '+91 98405 23456', license_number: 'TN-10-2016-00887', current_lat: 12.9249, current_lng: 80.1000, availability_status: 'AVAILABLE', shift_start: '06:00', shift_end: '18:00', assigned_lorry_id: 'lorry-14', performance_score: 92, total_deliveries: 410, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'driver-15', name: 'Harish Babu', phone: '+91 98804 34567', license_number: 'KA-04-2017-00554', current_lat: 13.0358, current_lng: 77.5970, availability_status: 'AVAILABLE', shift_start: '06:00', shift_end: '18:00', assigned_lorry_id: 'lorry-15', performance_score: 95, total_deliveries: 390, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'driver-16', name: 'Chandrasekar P', phone: '+91 94435 45678', license_number: 'TN-42-2015-00221', current_lat: 11.1085, current_lng: 77.3411, availability_status: 'AVAILABLE', shift_start: '05:30', shift_end: '17:30', assigned_lorry_id: 'lorry-16', performance_score: 94, total_deliveries: 670, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'driver-17', name: 'Nagarajan Swami', phone: '+91 94436 56789', license_number: 'TN-33-2016-00667', current_lat: 11.3410, current_lng: 77.7172, availability_status: 'AVAILABLE', shift_start: '06:00', shift_end: '18:00', assigned_lorry_id: 'lorry-17', performance_score: 91, total_deliveries: 330, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'driver-18', name: 'Kandasamy M', phone: '+91 94437 67890', license_number: 'TN-67-2018-00441', current_lat: 9.5916, current_lng: 77.9511, availability_status: 'AVAILABLE', shift_start: '06:30', shift_end: '18:30', assigned_lorry_id: 'lorry-18', performance_score: 93, total_deliveries: 290, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'driver-19', name: 'Arun Mozhi Varman', phone: '+91 98406 78901', license_number: 'TN-07-2019-00119', current_lat: 13.0100, current_lng: 80.2100, availability_status: 'UNAVAILABLE', shift_start: '06:00', shift_end: '18:00', assigned_lorry_id: null, performance_score: 88, total_deliveries: 150, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'driver-20', name: 'Pradeep Shetty', phone: '+91 98805 89012', license_number: 'KA-20-2015-00773', current_lat: 12.9500, current_lng: 77.6000, availability_status: 'OFF_DUTY', shift_start: '20:00', shift_end: '08:00', assigned_lorry_id: null, performance_score: 90, total_deliveries: 540, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'driver-21', name: 'Vijay Shanthi', phone: '+91 98407 90123', license_number: 'TN-11-2018-00994', current_lat: 12.9180, current_lng: 80.1400, availability_status: 'AVAILABLE', shift_start: '06:00', shift_end: '18:00', assigned_lorry_id: 'lorry-21', performance_score: 96, total_deliveries: 380, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'driver-22', name: 'Shankar Lingam', phone: '+91 94438 01234', license_number: 'TN-72-2016-00332', current_lat: 8.7139, current_lng: 77.7567, availability_status: 'AVAILABLE', shift_start: '06:00', shift_end: '18:00', assigned_lorry_id: 'lorry-22', performance_score: 94, total_deliveries: 460, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'driver-23', name: 'Arockiasamy T', phone: '+91 94439 12345', license_number: 'TN-88-2017-00551', current_lat: 10.7905, current_lng: 78.7047, availability_status: 'AVAILABLE', shift_start: '06:00', shift_end: '18:00', assigned_lorry_id: 'lorry-23', performance_score: 92, total_deliveries: 310, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'driver-24', name: 'Ramanathan Iyer', phone: '+91 94440 23456', license_number: 'TN-45-2015-00889', current_lat: 10.7870, current_lng: 79.1378, availability_status: 'AVAILABLE', shift_start: '06:00', shift_end: '18:00', assigned_lorry_id: 'lorry-24', performance_score: 95, total_deliveries: 590, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  // Standby drivers pool
  { id: 'driver-25', name: 'Balaraman S', phone: '+91 98408 34567', license_number: 'TN-01-2020-00445', current_lat: 13.0827, current_lng: 80.2707, availability_status: 'AVAILABLE', shift_start: '06:00', shift_end: '18:00', assigned_lorry_id: null, performance_score: 91, total_deliveries: 120, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'driver-26', name: 'Ganesh Moorthy', phone: '+91 98409 45678', license_number: 'TN-03-2019-00223', current_lat: 13.0600, current_lng: 80.2300, availability_status: 'AVAILABLE', shift_start: '06:00', shift_end: '18:00', assigned_lorry_id: null, performance_score: 93, total_deliveries: 180, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'driver-27', name: 'Naveen Prashanth', phone: '+91 98806 56789', license_number: 'KA-01-2021-00119', current_lat: 12.9800, current_lng: 77.6000, availability_status: 'AVAILABLE', shift_start: '06:00', shift_end: '18:00', assigned_lorry_id: null, performance_score: 90, total_deliveries: 95, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'driver-28', name: 'Raghavan Pillai', phone: '+91 94441 67890', license_number: 'KL-01-2016-00443', current_lat: 11.0000, current_lng: 76.9600, availability_status: 'AVAILABLE', shift_start: '06:00', shift_end: '18:00', assigned_lorry_id: null, performance_score: 95, total_deliveries: 430, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'driver-29', name: 'Thirunavukkarasu V', phone: '+91 94442 78901', license_number: 'TN-49-2017-00661', current_lat: 10.9500, current_lng: 78.0800, availability_status: 'AVAILABLE', shift_start: '06:00', shift_end: '18:00', assigned_lorry_id: null, performance_score: 92, total_deliveries: 260, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'driver-30', name: 'Sivakumar Natarajan', phone: '+91 94443 89012', license_number: 'TN-28-2015-00774', current_lat: 11.6500, current_lng: 78.1500, availability_status: 'AVAILABLE', shift_start: '06:00', shift_end: '18:00', assigned_lorry_id: null, performance_score: 94, total_deliveries: 390, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'driver-31', name: 'Dinesh Karthik M', phone: '+91 98410 90123', license_number: 'TN-02-2020-00881', current_lat: 13.0700, current_lng: 80.2500, availability_status: 'AVAILABLE', shift_start: '07:00', shift_end: '19:00', assigned_lorry_id: null, performance_score: 89, total_deliveries: 110, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'driver-32', name: 'Jayaprakash Mani', phone: '+91 98411 01234', license_number: 'TN-05-2018-00332', current_lat: 13.1000, current_lng: 80.2000, availability_status: 'AVAILABLE', shift_start: '06:00', shift_end: '18:00', assigned_lorry_id: null, performance_score: 96, total_deliveries: 340, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
];

// Helper to generate 80+ realistic shipments with varied weights, deadlines, priorities, same-city clusters & impossible edge cases
function generateSeedShipments(): Shipment[] {
  const shipments: Shipment[] = [
    // 1. Killer Demo Shipment (S-1042)
    {
      id: 'shipment-1042',
      shipment_code: 'S-1042',
      customer_id: 'cust-chennai-auto',
      customer_name: 'Apex Precision Engineering Ltd',
      description: 'CNC Machined Transmission Casings (3.2 Ton)',
      pickup_lat: 13.0827,
      pickup_lng: 80.2707,
      pickup_address: 'Chennai Port Container Freight Station',
      pickup_city: 'Chennai',
      destination_lat: 12.8399,
      destination_lng: 77.6770,
      destination_address: 'Hosur SIPCOT Industrial Complex, Phase 1',
      destination_city: 'Hosur',
      weight_kg: 3200,
      volume_m3: 11.5,
      category: 'AUTOMOTIVE',
      priority: 'HIGH',
      delivery_deadline: new Date(Date.now() + 18 * 3600 * 1000).toISOString(),
      status: 'PENDING',
      value_inr: 450000,
      created_at: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
      updated_at: new Date().toISOString(),
    },
    // Same destination consolidation cluster: Chennai -> Hosur / Bengaluru
    {
      id: 'shipment-1043',
      shipment_code: 'S-1043',
      customer_id: 'cust-chennai-auto',
      customer_name: 'Apex Precision Engineering Ltd',
      description: 'Industrial Fasteners & Bushings (1.8 Ton)',
      pickup_lat: 13.0850,
      pickup_lng: 80.2100,
      pickup_address: 'Ambattur Industrial Estate',
      pickup_city: 'Chennai',
      destination_lat: 12.8450,
      destination_lng: 77.6850,
      destination_address: 'Hosur Automotive Ancillary Yard',
      destination_city: 'Hosur',
      weight_kg: 1800,
      volume_m3: 6.2,
      category: 'AUTOMOTIVE',
      priority: 'HIGH',
      delivery_deadline: new Date(Date.now() + 20 * 3600 * 1000).toISOString(),
      status: 'PENDING',
      value_inr: 280000,
      created_at: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
      updated_at: new Date().toISOString(),
    },
    // Karur -> Chennai Textile Cluster (S-101, S-102, S-104)
    {
      id: 'shipment-101',
      shipment_code: 'S-101',
      customer_id: 'cust-karur-textiles',
      customer_name: 'Karur Home Textiles Export Corp',
      description: 'Organic Cotton Bedding & Jacquard Linens (2.2 Ton)',
      pickup_lat: 10.9601,
      pickup_lng: 78.0766,
      pickup_address: 'Karur Textile Freight Terminal, Thanthoni',
      pickup_city: 'Karur',
      destination_lat: 13.0827,
      destination_lng: 80.2707,
      destination_address: 'Chennai Sea Port CFS Gateway',
      destination_city: 'Chennai',
      weight_kg: 2200,
      volume_m3: 9.0,
      category: 'TEXTILE',
      priority: 'CRITICAL',
      delivery_deadline: new Date(Date.now() + 24 * 3600 * 1000).toISOString(),
      status: 'PENDING',
      value_inr: 890000,
      created_at: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'shipment-102',
      shipment_code: 'S-102',
      customer_id: 'cust-karur-textiles',
      customer_name: 'Karur Home Textiles Export Corp',
      description: 'Export Curtains & Towel Consignment (1.9 Ton)',
      pickup_lat: 10.9650,
      pickup_lng: 78.0800,
      pickup_address: 'Vengamedu Weaving Park',
      pickup_city: 'Karur',
      destination_lat: 13.0890,
      destination_lng: 80.2800,
      destination_address: 'Chennai Sea Port CFS Gateway',
      destination_city: 'Chennai',
      weight_kg: 1900,
      volume_m3: 7.8,
      category: 'TEXTILE',
      priority: 'HIGH',
      delivery_deadline: new Date(Date.now() + 26 * 3600 * 1000).toISOString(),
      status: 'PENDING',
      value_inr: 650000,
      created_at: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'shipment-104',
      shipment_code: 'S-104',
      customer_id: 'cust-karur-yarns',
      customer_name: 'Cauvery Cotton Mills',
      description: 'Bleached Cotton Yarn Rolls (2.4 Ton)',
      pickup_lat: 10.9580,
      pickup_lng: 78.0720,
      pickup_address: 'Gandhigram Textile Warehouse',
      pickup_city: 'Karur',
      destination_lat: 13.0750,
      destination_lng: 80.2600,
      destination_address: 'Madhavaram Apparel Hub',
      destination_city: 'Chennai',
      weight_kg: 2400,
      volume_m3: 8.5,
      category: 'TEXTILE',
      priority: 'HIGH',
      delivery_deadline: new Date(Date.now() + 28 * 3600 * 1000).toISOString(),
      status: 'PENDING',
      value_inr: 540000,
      created_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
      updated_at: new Date().toISOString(),
    },
    // Coimbatore -> Bengaluru Engineering Cluster
    {
      id: 'shipment-105',
      shipment_code: 'S-105',
      customer_id: 'cust-cbe-pumps',
      customer_name: 'Kirloskar & CRI Pumps Consortium',
      description: 'Submersible Agricultural Pump Sets (4.8 Ton)',
      pickup_lat: 11.0168,
      pickup_lng: 76.9558,
      pickup_address: 'Ganapathy Industrial Area',
      pickup_city: 'Coimbatore',
      destination_lat: 12.9716,
      destination_lng: 77.5946,
      destination_address: 'Peenya Industrial Complex, 3rd Stage',
      destination_city: 'Bengaluru',
      weight_kg: 4800,
      volume_m3: 15.2,
      category: 'AUTOMOTIVE',
      priority: 'HIGH',
      delivery_deadline: new Date(Date.now() + 22 * 3600 * 1000).toISOString(),
      status: 'PENDING',
      value_inr: 1200000,
      created_at: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'shipment-106',
      shipment_code: 'S-106',
      customer_id: 'cust-cbe-motors',
      customer_name: 'Lakshmi Electrical Drives',
      description: 'Three-Phase Electric Motors (3.1 Ton)',
      pickup_lat: 11.0250,
      pickup_lng: 76.9700,
      pickup_address: 'SIDCO Industrial Estate, Kurichi',
      pickup_city: 'Coimbatore',
      destination_lat: 12.9900,
      destination_lng: 77.5800,
      destination_address: 'Rajajinagar Industrial Town',
      destination_city: 'Bengaluru',
      weight_kg: 3100,
      volume_m3: 9.8,
      category: 'ELECTRONICS',
      priority: 'MEDIUM',
      delivery_deadline: new Date(Date.now() + 30 * 3600 * 1000).toISOString(),
      status: 'PENDING',
      value_inr: 720000,
      created_at: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
      updated_at: new Date().toISOString(),
    },
    // Perishable / Reefer Requirement
    {
      id: 'shipment-107',
      shipment_code: 'S-107',
      customer_id: 'cust-erode-dairy',
      customer_name: 'Aavin Dairy & Cold Logistics',
      description: 'Pasteurized Butter & Fresh Dairy (2.1 Ton - 4°C Reefer)',
      pickup_lat: 11.3410,
      pickup_lng: 77.7172,
      pickup_address: 'Erode Dairy Processing Plant',
      pickup_city: 'Erode',
      destination_lat: 13.0827,
      destination_lng: 80.2707,
      destination_address: 'Koyambedu Cold Chain Facility',
      destination_city: 'Chennai',
      weight_kg: 2100,
      volume_m3: 8.0,
      category: 'PERISHABLE',
      priority: 'CRITICAL',
      delivery_deadline: new Date(Date.now() + 14 * 3600 * 1000).toISOString(),
      status: 'PENDING',
      value_inr: 420000,
      created_at: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
      updated_at: new Date().toISOString(),
    },
    // Impossible / Extreme Weight Edge Case (32 Ton - Exceeds max vehicle capacity 28T)
    {
      id: 'shipment-999',
      shipment_code: 'S-999-OVERWEIGHT',
      customer_id: 'cust-salem-steel',
      customer_name: 'Salem Heavy Forgings Authority',
      description: 'Monolithic Blast Furnace Crane Ring (32 Ton Single Piece)',
      pickup_lat: 11.6643,
      pickup_lng: 78.1460,
      pickup_address: 'Salem Steel Plant Gate 4',
      pickup_city: 'Salem',
      destination_lat: 13.0827,
      destination_lng: 80.2707,
      destination_address: 'Chennai Ennore Port Special Wharf',
      destination_city: 'Chennai',
      weight_kg: 32000, // Impossible single load
      volume_m3: 65.0,
      category: 'GENERAL',
      priority: 'MEDIUM',
      delivery_deadline: new Date(Date.now() + 36 * 3600 * 1000).toISOString(),
      status: 'PENDING',
      value_inr: 3500000,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    // Impossible Deadline Edge Case (Past deadline / 30 mins for 400km journey)
    {
      id: 'shipment-998',
      shipment_code: 'S-998-IMPOSSIBLE-ETA',
      customer_id: 'cust-quick-pharma',
      customer_name: 'Biopharma Urgent Diagnostics',
      description: 'Temperature-Sensitive Vaccine Serum (150 kg)',
      pickup_lat: 10.9601,
      pickup_lng: 78.0766,
      pickup_address: 'Karur Medical Depot',
      pickup_city: 'Karur',
      destination_lat: 13.0827,
      destination_lng: 80.2707,
      destination_address: 'Chennai Apollo Hospital Central Blood Bank',
      destination_city: 'Chennai',
      weight_kg: 150,
      volume_m3: 0.8,
      category: 'PERISHABLE',
      priority: 'CRITICAL',
      delivery_deadline: new Date(Date.now() + 45 * 60 * 1000).toISOString(), // 45 minutes for 400km!
      status: 'PENDING',
      value_inr: 950000,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ];

  // Procedurally generate the remaining 70+ diverse shipments across standard corridors
  const corridors = [
    { from: { city: 'Bengaluru', lat: 12.9716, lng: 77.5946, addr: 'Peenya Industrial Area' }, to: { city: 'Chennai', lat: 13.0827, lng: 80.2707, addr: 'Guindy Industrial Hub' } },
    { from: { city: 'Chennai', lat: 13.0827, lng: 80.2707, addr: 'Ambattur Estate' }, to: { city: 'Coimbatore', lat: 11.0168, lng: 76.9558, addr: 'SIDCO Industrial Zone' } },
    { from: { city: 'Karur', lat: 10.9601, lng: 78.0766, addr: 'Karur Export Terminal' }, to: { city: 'Bengaluru', lat: 12.9716, lng: 77.5946, addr: 'Whitefield Freight Park' } },
    { from: { city: 'Tirupur', lat: 11.1085, lng: 77.3411, addr: 'KNP Apparel Park' }, to: { city: 'Chennai', lat: 13.0827, lng: 80.2707, addr: 'Madhavaram Depot' } },
    { from: { city: 'Madurai', lat: 9.9252, lng: 78.1198, addr: 'Kappalur Industrial Area' }, to: { city: 'Salem', lat: 11.6643, lng: 78.1460, addr: 'Salem Bypass Warehouse' } },
    { from: { city: 'Hyderabad', lat: 17.3850, lng: 78.4867, addr: 'Sanathnagar Cargo Hub' }, to: { city: 'Bengaluru', lat: 12.9716, lng: 77.5946, addr: 'Electronic City Phase 1' } },
    { from: { city: 'Salem', lat: 11.6643, lng: 78.1460, addr: 'Ammapet Steel Yard' }, to: { city: 'Hosur', lat: 12.8399, lng: 77.6770, addr: 'Hosur Tech Logistics Park' } },
    { from: { city: 'Bengaluru', lat: 12.9716, lng: 77.5946, addr: 'Bommasandra Industrial Yard' }, to: { city: 'Karur', lat: 10.9601, lng: 78.0766, addr: 'Thanthoni Weaving Center' } },
    { from: { city: 'Coimbatore', lat: 11.0168, lng: 76.9558, addr: 'Singanallur Machine Works' }, to: { city: 'Madurai', lat: 9.9252, lng: 78.1198, addr: 'Melur Freight Yard' } },
    { from: { city: 'Chennai', lat: 13.0827, lng: 80.2707, addr: 'Sriperumbudur Auto Park' }, to: { city: 'Hyderabad', lat: 17.3850, lng: 78.4867, addr: 'Patancheru Industrial Area' } },
  ];

  const categories = ['GENERAL', 'TEXTILE', 'AUTOMOTIVE', 'ELECTRONICS', 'AGRICULTURE', 'FRAGILE'] as const;
  const priorities = ['HIGH', 'MEDIUM', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL'] as const;
  const descriptions = [
    'Automotive Die-Cast Components',
    'Cotton Spun Yarn Bundles',
    'Electronic Circuit Assemblies',
    'Precision Lathe Tooling',
    'Agricultural Fertilisers & Seeds',
    'FMCG Packaged Goods',
    'Solar Inverter Sub-assemblies',
    'Industrial Hydraulic Valves',
    'Ceramic Tiles & Sanitaryware',
    'Knitted Hosiery Garments',
  ];

  for (let i = 8; i <= 82; i++) {
    const corridor = corridors[i % corridors.length];
    const category = categories[i % categories.length];
    const priority = priorities[i % priorities.length];
    const desc = descriptions[i % descriptions.length];
    
    // Varied weights between 400 kg and 5,500 kg
    const weight = 400 + ((i * 180) % 5200);
    const volume = Number((weight / 350).toFixed(2));
    
    // Random deadline between +12 hours and +48 hours
    const deadlineHours = 12 + ((i * 3) % 36);
    const deadline = new Date(Date.now() + deadlineHours * 3600 * 1000).toISOString();

    shipments.push({
      id: `shipment-${1000 + i}`,
      shipment_code: `S-${1000 + i}`,
      customer_id: `cust-in-${(i % 12) + 1}`,
      customer_name: `Southern Commercial Corp #${(i % 12) + 1}`,
      description: `${desc} (${(weight / 1000).toFixed(1)} Ton)`,
      pickup_lat: Number((corridor.from.lat + (Math.sin(i) * 0.03)).toFixed(4)),
      pickup_lng: Number((corridor.from.lng + (Math.cos(i) * 0.03)).toFixed(4)),
      pickup_address: corridor.from.addr,
      pickup_city: corridor.from.city,
      destination_lat: Number((corridor.to.lat + (Math.cos(i) * 0.03)).toFixed(4)),
      destination_lng: Number((corridor.to.lng + (Math.sin(i) * 0.03)).toFixed(4)),
      destination_address: corridor.to.addr,
      destination_city: corridor.to.city,
      weight_kg: weight,
      volume_m3: volume,
      category,
      priority,
      delivery_deadline: deadline,
      status: 'PENDING',
      value_inr: 150000 + (weight * 120),
      created_at: new Date(Date.now() - (i % 24) * 3600 * 1000).toISOString(),
      updated_at: new Date().toISOString(),
    });
  }

  return shipments;
}

export const SEED_SHIPMENTS: Shipment[] = generateSeedShipments();
